### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by jakiisheep** [davidsongoap/yper#1]
When trying to run the game I get an error:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from game_screen import GameScreen, ScreenType
  File "C:\Users\sheep\yper\game_screen.py", line 10, in <module>
    from screens import *
  File "C:\Users\sheep\yper\screens\__init__.py", line 5, in <module>
    from .play_screen import PlayScreen
  File "C:\Users\sheep\yper\screens\play_screen.py", line 16, in <module>
    from util import fetch_words
  File "C:\Users\sheep\yper\util.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Nevermind fixed the error above but it gives me another error:**

Traceback (most recent call last):
  File "main.py", line 78, in <module>
    game.run()
  File "main.py", line 69, in run
    self.draw()
  File "main.py", line 73, in draw
    self.screen.draw()
  File "C:\Users\sheep\yper\game_screen.py", line 46, in draw
    self.screens[self.game.current_screen.value].draw()
  File "C:\Users\sheep\yper\screens\menu_screen.py", line 69, in draw
    b.draw()
  File "C:\Users\sheep\yper\screens\buttons.py", line 45, in draw
    pygame.draw.rect(self.game.win, background_color,
TypeError: rect() takes no keyword arguments

**Comment by davidsongoap** [comment]
I think your problem is happening because you're not using pygame **v2** 
Try installing it first with 
`python -m pip install pygame==2.0.0.dev12`

**Comment by jakiisheep** [comment]
I was using the wrong version of pygame, v1 instead of v2
